# Classes
PoissonFiniteElement.o: PoissonFiniteElement.hpp PoissonFiniteElement.cpp
GaussQuad.o: GaussQuad.hpp GaussQuad.cpp

# Executables
poisson.x: poisson.o PoissonFiniteElement.o GaussQuad.o
